<?php 
/**
 * Progress Review opcheckout js
 *
 * @category    Aydus
 * @package     Aydus_ProgressReview
 * @author		Aydus <davidt@aydus.com>
 */
?>
<script type="application/javascript">
	checkout.progressReviewUrl = '<?php echo $this->getUrl('progressreview/progress/review') ?>';
</script>
<script type="application/javascript" src="<?php echo $this->getSkinUrl('js/aydus/progressreview.js'); ?>"></script>
